definitions:
  auth.LoginInput:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.LoginOutput:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/auth.LoginUser'
    type: object
  auth.LoginUser:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login handler
      parameters:
      - description: Login details
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/auth.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginOutput'
      summary: Login
      tags:
      - Authentication
swagger: "2.0"
